import os
import glob
import shutil
import argparse
import multiprocessing
from typing import List
from uuid import uuid4

from tqdm import tqdm

from vrdu import logger
from vrdu import utils
from vrdu import renderer
from vrdu import preprocess
from vrdu.annotation import LayoutAnnotation
from vrdu.config import config


log_file = str(uuid4()) + ".log"
log = logger.setup_app_level_logger(file_name=log_file, level="INFO", mode="a")


def extract_tex_files(path) -> List[str]:
    """
    Given a path, this function extracts all the MAIN .tex files within the
    specified directory and its subdirectories.

    Args:
        path (str): The path to the directory where the .tex files are located.

    Returns:
        List[str]: A list of paths to the .tex files found.
    """
    tex_files = []

    for root, dirs, files in os.walk(path):
        for file in files:
            # skip non-tex files
            if not file.endswith(".tex"):
                continue
            # skip paper_*.tex files
            if file.startswith("paper_"):
                continue
            tex_file = os.path.join(root, file)

            try:
                with open(tex_file, "r") as f:
                    content = f.read()
            except UnicodeDecodeError:
                continue

            # skip if this tex is not the main document
            if "\\begin{document}" not in content:
                continue

            tex_files.append(tex_file)
    return tex_files


def transform_tex_to_images(path):
    files = glob.glob(f"{path}/paper_*.tex")
    for file in tqdm(files):
        log.debug(f"Processing file: {file}")
        utils.compile_latex(file)
        pdf_file = os.path.splitext(file)[0] + ".pdf"
        output_dir = parse_file_name(file)
        os.makedirs(os.path.join(path, f"output/{output_dir}"), exist_ok=True)
        output_pdf = os.path.join(path, f"output/{output_dir}/paper.pdf")
        shutil.move(pdf_file, output_pdf)

        # convert into images
        utils.pdf2jpg(output_pdf, os.path.dirname(output_pdf))


def remove_redundant_files(path: str) -> None:
    """
    Remove redundant files generated by the script from the specified path.

    Parameters:
        path (str): The path where the files are located.

    Returns:
        None
    """
    # remove generated tex related files
    files = glob.glob(f"{path}/paper_*")
    for file in files:
        os.remove(file)

    # remove useless pdf and image files
    output_path = os.path.join(path, "output")
    for root, dirs, files in os.walk(output_path):
        for dir in dirs:
            if dir.startswith("block_"):
                shutil.rmtree(os.path.join(root, dir))


def process_one_file(file_name):
    original_cwd = os.getcwd()
    path = os.path.dirname(file_name)
    log.info(f"[VRDU] processing file {file_name}")

    # check if this paper has been processed
    quality_report_file = os.path.join(path, "output/result/quality_report.json")
    if os.path.exists(quality_report_file):
        log.info(f"[VRDU] File {file_name} has been processed")
        return

    try:
        os.chdir(path)
        # make a copy of the original tex file
        original_tex = os.path.join(path, "paper_original.tex")
        shutil.copyfile(file_name, original_tex)
        # preprocess
        log.info(f"[VRDU] Pre-processing file {original_tex}")
        preprocess.run(original_tex)

        # run rendering
        vrdu_renderer = renderer.Renderer()
        vrdu_renderer.render(original_tex)

        # compile into PDFs, and then convert into images
        log.info("[VRDU] Transforming from TEX to images, this may take a while...")
        transform_tex_to_images(path)

        # generate annotations
        log.info("[VRDU] Generating annotations, this may take a while...")
        vrdu_annotation = LayoutAnnotation(path)
        vrdu_annotation.annotate()
        log.info(f"[VRDU] Successfully processing file {file_name}")

    except Exception as e:
        error_type = e.__class__.__name__
        error_info = str(e)
        log.error(f"Error processing file {file_name}, type: {error_type}, message: {error_info}")

    finally:
        os.chdir(original_cwd)
        remove_redundant_files(path)


def process_one_category(path, cpu_count, category):
    category_path = os.path.join(path, category)
    log.info(f"path to raw data: {category_path}")
    log.info(f"Using cpu counts: {cpu_count}")
    tex_files = extract_tex_files(category_path)
    log.info(f"Found {len(tex_files)} tex files")

    with multiprocessing.Pool(cpu_count) as pool:
        pool.map(process_one_file, tex_files)
    # save log file
    shutil.move(log_file, f"batch_process_{category}.log")


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("-p", "--path", type=str, required=True)
    parser.add_argument("-c", "--cpu_count", type=int, required=True)
    parser.add_argument("-t", "--category", type=str, required=False)
    args = parser.parse_args()
    path, cpu_count, category = args.path, args.cpu_count, args.category

    categories = [category] if category is not None else utils.get_all_categories()

    for category in categories:
        log.info(f"Processing single category: {category}")
        process_one_category(path, cpu_count, category)
