import os
import re
import glob
import shutil
import argparse
import multiprocessing

from tqdm import tqdm

from vrdu import logger
from vrdu import utils
from vrdu import renderer
from vrdu import preprocess
from vrdu.annotation import LayoutAnnotation

log = logger.setup_app_level_logger(
    file_name="batch_process.log", level="INFO", mode="a"
)


def parse_file_name(filename) -> str:
    pattern = r"paper_(.*?)\.tex"
    match = re.search(pattern, filename)

    if not match:
        raise ValueError("File name does not match the pattern")

    return match.group(1)


def transform_tex_to_images(path):
    files = glob.glob(f"{path}/paper_*.tex")
    for file in tqdm(files):
        log.debug(f"Processing file: {file}")
        utils.compile_latex(file)
        pdf_file = os.path.splitext(file)[0] + ".pdf"
        output_dir = parse_file_name(file)
        os.makedirs(os.path.join(path, f"output/{output_dir}"), exist_ok=True)
        output_pdf = os.path.join(path, f"output/{output_dir}/paper.pdf")
        shutil.move(pdf_file, output_pdf)

        # convert into images
        utils.pdf2jpg(output_pdf, os.path.dirname(output_pdf))


def remove_redundant_files(path: str) -> None:
    """
    Remove redundant files generated by the script from the specified path.

    Parameters:
        path (str): The path where the files are located.

    Returns:
        None
    """
    # remove generated tex related files
    files = glob.glob(f"{path}/paper_*")
    for file in files:
        os.remove(file)

    # remove useless pdf and image files
    output_path = os.path.join(path, "output")
    for root, dirs, files in os.walk(output_path):
        for dir in dirs:
            if dir.startswith("block_"):
                shutil.rmtree(os.path.join(root, dir))


def process_one_file(file_name):
    original_cwd = os.getcwd()
    path = os.path.dirname(file_name)
    log.info(f"[VRDU] processing file {file_name}")

    # check if this paper has been processed
    quality_report_file = os.path.join(path, "output/result/quality_report.json")
    if os.path.exists(quality_report_file):
        log.info(f"[VRDU] File {file_name} has been processed")
        return

    try:
        os.chdir(path)
        # make a copy of the original tex file
        original_tex = os.path.join(path, "paper_original.tex")
        shutil.copyfile(file_name, original_tex)
        # preprocess
        log.info(f"[VRDU] Pre-processing file {original_tex}")
        preprocess.run(original_tex)

        # run rendering
        vrdu_renderer = renderer.Renderer()
        vrdu_renderer.render(original_tex)

        # compile into PDFs, and then convert into images
        log.info("[VRDU] Transforming from TEX to images, this may take a while...")
        transform_tex_to_images(path)

        # generate annotations
        log.info("[VRDU] Generating annotations, this may take a while...")
        vrdu_annotation = LayoutAnnotation(path)
        vrdu_annotation.annotate()

    except Exception as e:
        log.error(f"Error processing file {file_name}: {e}")

    finally:
        log.info(f"[VRDU] Finished processing file {file_name}")
        os.chdir(original_cwd)
        remove_redundant_files(path)


def main(path, cpu_count=1):
    log.info(f"path to raw data: {path}")
    log.info(f"Using cpu counts: {cpu_count}")
    tex_files = utils.extract_tex_files(path)
    log.info(f"Found {len(tex_files)} tex files")

    with multiprocessing.Pool(cpu_count) as pool:
        pool.map(process_one_file, tex_files)


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("-p", "--path", type=str, required=True)
    parser.add_argument("-c", "--cpu_count", type=int, required=True)
    args = parser.parse_args()
    path, cpu_count = args.path, args.cpu_count

    categories = utils.get_all_categories()
    for category in categories:
        category_path = os.path.join(path, category)
        log.info(f"Processing category: {category_path}")
        main(category_path, cpu_count)
