import os
import re
import glob
import shutil
import argparse
import multiprocessing
from functools import partial

from tqdm import tqdm

from vrdu import logger
from vrdu import utils
from vrdu import renderer
from vrdu import preprocess
from vrdu.annotation import LayoutAnnotation

log = logger.setup_app_level_logger(file_name="app_debug.log")


def extract_tex_files(path):
    tex_files = []

    for root, dirs, files in os.walk(path):
        for file in files:
            if not file.endswith(".tex"):
                continue
            if file.startswith("paper_"):
                continue
            tex_file = os.path.join(root, file)

            try:
                with open(tex_file) as f:
                    content = f.read()
            except UnicodeDecodeError:
                continue

            if "\\begin{document}" not in content:
                continue

            tex_files.append(tex_file)
    return tex_files


def parse_file_name(filename) -> str:
    pattern = r"paper_(.*?)\.tex"
    match = re.search(pattern, filename)

    if not match:
        raise ValueError("File name does not match the pattern")

    return match.group(1)


def transform_tex_to_images(path):
    files = glob.glob(f"{path}/paper_*.tex")
    for file in tqdm(files):
        log.debug(f"Processing file: {file}")
        utils.compile_latex(file)
        pdf_file = os.path.splitext(file)[0] + ".pdf"
        output_dir = parse_file_name(file)
        os.makedirs(os.path.join(path, f"output/{output_dir}"), exist_ok=True)
        output_pdf = os.path.join(path, f"output/{output_dir}/paper.pdf")
        shutil.move(pdf_file, output_pdf)

        # convert into images
        utils.pdf2jpg(output_pdf, os.path.dirname(output_pdf))


def remove_redundant_files(path: str) -> None:
    """
    Remove redundant files generated by the script from the specified path.

    Parameters:
        path (str): The path where the files are located.

    Returns:
        None
    """
    # remove generated tex related files
    files = glob.glob(f"{path}/paper_*")
    for file in files:
        os.remove(file)

    # remove useless pdf and image files
    output_path = os.path.join(path, "output")
    for root, dirs, files in os.walk(output_path):
        for dir in dirs:
            if dir.startswith("block_"):
                shutil.rmtree(os.path.join(root, dir))


def process_one_file(file_name, success_save_path):
    original_cwd = os.getcwd()
    path = os.path.dirname(file_name)
    tex_folder_path = os.path.basename(path)

    process_result = {'file': file_name, 'status': 'Success'}

    # check if this paper has been processed
    quality_report_file = os.path.join(path, "output/result/quality_report.json")
    if os.path.exists(quality_report_file):
        # this paper has been processed
        return process_result

    try:
        os.chdir(path)  # 改变工作目录到文件所在目录

        log.info(f"[VRDU] processing file {file_name}")

        # make a copy of the original tex file
        original_tex = os.path.join(path, "paper_original.tex")
        shutil.copyfile(file_name, original_tex)
        # preprocess
        log.info(f"[VRDU] Pre-processing file {original_tex}")
        preprocess.run(original_tex)

        # run rendering
        vrdu_renderer = renderer.Renderer()
        vrdu_renderer.render(original_tex)

        # compile into PDFs, and then convert into images
        log.info("[VRDU] Transforming from TEX to images, this may take a while...")
        transform_tex_to_images(path)

        # generate annotations
        log.info("[VRDU] Generating annotations, this may take a while...")
        vrdu_annotation = LayoutAnnotation(path)
        vrdu_annotation.annotate()

        shutil.copytree(path, f'{success_save_path}/{tex_folder_path}')

    except Exception as e:
        process_result['status'] = 'Failed'
        # process_result['error'] = str(e)

    finally:
        os.chdir(original_cwd)
        remove_redundant_files(path)
        return process_result





def main(path, cpu_count=None):
    success_path = path + '_success'
    os.makedirs(success_path, exist_ok=True)
    tex_files = sorted(extract_tex_files(path))

    if cpu_count is None:
        cpu_count = os.cpu_count()
    log.info(f'Using cpu counts: {cpu_count}')
    
    with multiprocessing.Pool(cpu_count) as pool:
        func = partial(process_one_file, success_save_path=success_path)
        results = pool.map(func, tex_files)

    success_files = set(result['file'] for result in results if result['status'] == 'Success')
    failed_files = set((result['file'], result.get('error', '')) for result in results if result['status'] == 'Failed')

    # 将成功的文件名写入到 success_files.txt
    with open('success_files.txt', 'w') as file:
        for filename in success_files:
            file.write(filename + "\n")

    # 将失败的文件名和错误信息写入到 failed_files.txt
    with open('failed_files.txt', 'w') as file:
        for filename, error in failed_files:
            file.write(f"{filename}: {error}\n")

    success_count, failure_count = len(success_files), len(failed_files)
    all_count = success_count + failure_count

    print(f"number of successful files: {len(success_files)}, success rate: {success_count / all_count}")


if __name__ == "__main__":
    # parser = argparse.ArgumentParser()
    # parser.add_argument("-p", "--path", type=str, required=True)
    # args = parser.parse_args()
    # path = args.path
    path = os.path.expanduser("/cpfs01/user/penghaoyang/code/vrdu_data_process/vrdu_arxiv")
    main(path)
