import argparse
import glob
import os
import re
import shutil
import subprocess
from tqdm import tqdm


from vrdu import logger
from vrdu import utils
from vrdu import renderer
from vrdu import preprocess
from vrdu.annotation import LayoutAnnotation


log = logger.setup_app_level_logger(file_name="app_debug.log")


def parse_file_name(filename) -> str:
    pattern = r"paper_(.*?)\.tex"
    match = re.search(pattern, filename)

    if not match:
        raise ValueError("File name does not match the pattern")

    return match.group(1)


def transform_tex_to_images(path):
    try:
        with open("paper_output.log", "a") as f:
            subprocess.check_call(
                ["pdflatex", "-interaction=nonstopmode", "paper_colored.tex"],
                stdout=f,
                stderr=f,
            )
    except subprocess.CalledProcessError:
        raise RuntimeError(
            f"[VRDU] Level 2: {path}/paper_colored.tex is not compilable"
        )

    files = glob.glob(f"{path}/paper_*.tex")
    for file in tqdm(files):
        log.debug(f"Processing file: {file}")
        utils.compile_latex(file)
        pdf_file = os.path.splitext(file)[0] + ".pdf"
        output_dir = parse_file_name(file)
        os.makedirs(os.path.join(path, f"output/{output_dir}"), exist_ok=True)
        output_pdf = os.path.join(path, f"output/{output_dir}/paper.pdf")
        shutil.move(pdf_file, output_pdf)

        # convert into images
        utils.pdf2jpg(output_pdf, os.path.dirname(output_pdf))


def remove_redundant_files(path: str) -> None:
    """
    Remove redundant files generated by the script from the specified path.

    Parameters:
        path (str): The path where the files are located.

    Returns:
        None
    """
    # remove generated tex related files
    files = glob.glob(f"{path}/paper_*")
    for file in files:
        os.remove(file)

    # remove useless pdf and image files
    output_path = os.path.join(path, "output")
    for root, dirs, files in os.walk(output_path):
        for dir in dirs:
            if dir.startswith("block_"):
                shutil.rmtree(os.path.join(root, dir))


def parse_arguments():
    """
    Parses the command line arguments.

    Returns:
    - `file_name` (str): The name of the test file with full path.

    Required Arguments:
    - `--file_name` (str): The name of the test file with full path.

    Example Usage:
    ```
    python main.py --file_name /path/to/file.tex
    ```

    Raises:
    - `argparse.ArgumentError`: If the `--file_name` argument is not provided.
    """
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "-f",
        "--file_name",
        type=str,
        required=True,
        help="The name of the tes file will full path",
    )
    args = parser.parse_args()
    file_name = args.file_name

    return file_name


def cd_wrapper(func):
    """
    Wraps a function with a decorator that changes the current working directory to the directory of the file path argument,
    calls the original function, and then changes the directory back to the original directory.

    Parameters:
        func (function): The function to be wrapped.

    Returns:
        function: The wrapped function.
    """

    def wrapped(*args, **kwargs):
        # Get file path argument
        file_path = args[0]

        # Get directory and save current working dir
        directory = os.path.dirname(file_path)
        cwd = os.getcwd()

        # Change to directory
        os.chdir(directory)

        # Call original function
        result = func(*args, **kwargs)

        # Change back to original dir
        os.chdir(cwd)

        return result

    return wrapped


@cd_wrapper
def main(file_name) -> None:
    path = os.path.dirname(file_name)
    log.info(f"[VRDU] processing file {file_name}")

    # make a copy of the original tex file
    original_tex = os.path.join(path, "paper_original.tex")
    shutil.copyfile(file_name, original_tex)

    # preprocess
    try:
        log.info(f"[VRDU] Pre-processing file {original_tex}")
        preprocess.run(original_tex)

        # run rendering
        vrdu_renderer = renderer.Renderer()
        vrdu_renderer.render(original_tex)

        # compile into PDFs, and then convert into images
        log.info("[VRDU] Transforming from TEX to images, this may take a while...")
        transform_tex_to_images(path)

        # generate annotations
        log.info("[VRDU] Generating annotations, this may take a while...")
        vrdu_annotation = LayoutAnnotation(path)
        vrdu_annotation.annotate()

    finally:
        # remove redundant files
        remove_redundant_files(path)
    log.info(
        f"[VRDU] Results of processing {file_name} are saved in {path}/output/result"
    )


if __name__ == "__main__":
    file_name = parse_arguments()
    main(file_name)
