import argparse
import glob
import os
import re
import shutil
from typing import Dict
from tqdm import tqdm

from arxiv_cleaner.cleaner import Cleaner

from rendering.utils import export_to_json
from rendering import render_simple_env, render_complex_env

from scripts import output_layout_annotation

from logger import logger
import utils


log = logger.setup_app_level_logger(file_name="app_debug.log")


def clean_tex(original_tex):
    input_dir = os.path.dirname(original_tex)
    tex = os.path.basename(original_tex)

    # Create the command options
    command_options = {
        "latex": {
            "compiler": "pdflatex",
            "extra_args": "",
        },
        "bib": {
            "compiler": "bibtex",
            "extra_args": "",
        },
        "latexpand": {
            "extra_args": "",
        },
    }

    # Create the cleaner
    cleaner = Cleaner(
        input_dir=input_dir,
        output_dir=input_dir,
        tex=tex,
        command_options=command_options,
        verbose=False,
    )

    # Run the cleaner
    cleaner.clean()


def replace_pdf_figures_with_png(tex_file):
    path = os.path.dirname(tex_file)
    with open(tex_file) as f:
        content = f.read()

    # Regular expression pattern to match \includegraphics
    # commands with PDF files
    pattern = r"\\includegraphics(\[.*?\])?\{(.*?\.pdf)\}"

    # Find all matches of \includegraphics with PDF files
    matches = re.findall(pattern, content)

    # Replace PDF paths with PNG paths
    for match in matches:
        # crop the pdf image
        pdf_image_name = match[1]
        pdf_image = os.path.join(path, pdf_image_name)
        png_image_name = os.path.splitext(pdf_image_name)[0] + ".png"
        png_image = os.path.join(path, png_image_name)

        utils.convert_pdf_figure_to_png_image(pdf_image, png_image)

        # replace the reference in tex file
        content = content.replace(match[1], png_image_name)

    with open(tex_file, "w") as f:
        f.write(content)


def preprocess(original_tex: str) -> None:
    pass
    # Step 1: clean tex
    clean_tex(original_tex)

    # Step 2: process images
    replace_pdf_figures_with_png(original_tex)


def parse_file_name(filename) -> str:
    pattern = r"paper_(.*?)\.tex"
    match = re.search(pattern, filename)

    if not match:
        raise ValueError("File name does not match the pattern")

    return match.group(1)


def transform_tex_to_images(path):
    files = glob.glob(f"{path}/paper_*.tex")
    print("Transforming from TEX to images, this may take a while...")
    for file in tqdm(files):
        log.debug(f"Processing file: {file}")
        utils.compile_latex(file)
        pdf_file = os.path.splitext(file)[0] + ".pdf"
        log.debug(f"pdf_file: {pdf_file}")
        output_dir = parse_file_name(file)
        os.makedirs(os.path.join(path, f"output/{output_dir}"), exist_ok=True)
        output_pdf = os.path.join(path, f"output/{output_dir}/paper.pdf")
        log.debug(f"output_pdf: {output_pdf}")
        shutil.move(pdf_file, output_pdf)

        # convert into images
        utils.pdf2jpg(output_pdf, os.path.dirname(output_pdf))


def extract_metadata(log_file) -> Dict[str, float]:
    regex_pattern = r"\[vrdu_data_process: The (.*) is: ([-+]?\d+\.\d+)pt\]"

    extracted_data = {}

    with open(log_file, "r", encoding="latin-1") as file:
        log_content = file.read()

        for match in re.findall(regex_pattern, log_content):
            key = match[0]
            value = float(match[1])
            extracted_data[key] = value

    return extracted_data


def extract_layout_metadata(path: str) -> None:
    log_file = os.path.join(path, "paper_colored.log")
    out_path = os.path.join(path, "output/result/layout_metadata.json")
    extracted_data = extract_metadata(log_file)
    export_to_json(extracted_data, out_path)


def remove_redundant_files(path: str) -> None:
    """
    Remove redundant files generated by the script from the specified path.

    Parameters:
        path (str): The path where the files are located.

    Returns:
        None
    """
    # remove generated tex related files
    files = glob.glob(f"{path}/paper_*")
    for file in files:
        os.remove(file)

    # remove useless pdf and image files
    output_path = os.path.join(path, "output")
    for root, dirs, files in os.walk(output_path):
        for dir in dirs:
            if dir == "result":
                continue
            shutil.rmtree(os.path.join(root, dir))


def parse_arguments():
    """
    Parses the command line arguments.

    Returns:
    - `file_name` (str): The name of the test file with full path.

    Required Arguments:
    - `--file_name` (str): The name of the test file with full path.

    Example Usage:
    ```
    python main.py --file_name /path/to/file.tex
    ```

    Raises:
    - `argparse.ArgumentError`: If the `--file_name` argument is not provided.
    """
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--file_name",
        type=str,
        required=True,
        help="The name of the tes file will full path",
    )
    args = parser.parse_args()
    file_name = args.file_name

    return file_name


def main() -> None:
    file_name = parse_arguments()
    path = os.path.dirname(file_name)
    os.makedirs(os.path.join(path, "output/result"), exist_ok=True)

    original_tex = os.path.join(path, "paper_original.tex")
    shutil.copyfile(file_name, original_tex)

    # preprocess
    preprocess(original_tex)

    # run rendering
    render_simple_env.run(original_tex)
    render_complex_env.run(original_tex)

    # compile into PDFs, and then convert into images
    transform_tex_to_images(path)

    # extract layout metadata
    extract_layout_metadata(path)

    # generate annotations
    print("Generating annotations, this may take a while...")
    output_layout_annotation.main(path)

    # remove redundant files
    remove_redundant_files(path)


if __name__ == "__main__":
    main()
