import argparse
import os
import shutil
import subprocess
import tarfile
from typing import List
import zipfile
import glob


from logger import logger


log = logger.setup_app_level_logger(file_name="app_debug.log")


def extract_all_tar_gz(directory):
    for root, dirs, files in os.walk(directory):
        for file in files:
            if not file.endswith(".tar.gz"):
                continue
            file_path = os.path.join(root, file)
            extract_path = os.path.splitext(file_path)[0]
            extract_path = os.path.splitext(extract_path)[0]
            if os.path.exists(extract_path):
                continue
            extract_tar_gz(file_path, extract_path)


def extract_tar_gz(file_path, extract_path):
    with tarfile.open(file_path, "r:gz") as tar:
        tar.extractall(extract_path)


def find_all_tex_files(directory) -> List[str]:
    tex_files = []
    for root, dirs, files in os.walk(directory):
        for file in files:
            # skip the _rendered.tex files generated by us
            if file.endswith(".tex") and not file.endswith("_rendered.tex"):
                file_path = os.path.join(root, file)
                tex_files.append(file_path)
    return tex_files


def preprocess_tex_files(tex_files: List[str]) -> List[str]:
    result = []
    for tex_file in tex_files:
        try:
            with open(tex_file, "r") as file:
                # Perform operations on the file
                tex_text = file.read()
        except UnicodeDecodeError:
            with open(tex_file, "r", encoding="latin-1") as file:
                # Perform operations on the file
                tex_text = file.read()

        # check if it is a main tex file
        if tex_text.find(r"\begin{document}") == -1:
            continue

        result.append(tex_file)

    return result


def extract_result(source_dir, dest_dir):
    # Create the destination directory if it doesn't exist
    os.makedirs(dest_dir, exist_ok=True)

    # Iterate over the nested directories
    for root, dirs, files in os.walk(source_dir):
        if "output" not in dirs:
            continue
        if "result" not in os.listdir(os.path.join(root, "output")):
            continue

        result_dir = os.path.join(root, "output", "result")
        png_files = glob.glob(f"{result_dir}/*.png")
        if not png_files:
            continue

        # Construct the path to the "result" subdirectory
        result_dir = os.path.join(root, "output", "result")

        # Create a new directory in the destination directory
        new_dir = os.path.join(dest_dir, os.path.basename(root))
        os.makedirs(new_dir, exist_ok=True)

        # Copy the "result" subdirectory to the new directory
        shutil.copytree(result_dir, os.path.join(new_dir, os.path.basename(root)))

        # Zip the new directory
        file_path = os.path.join(dest_dir, f"{os.path.basename(root)}.zip")
        with zipfile.ZipFile(file_path, "w", zipfile.ZIP_DEFLATED) as zip_file:
            for folder_name, _, file_names in os.walk(new_dir):
                for file_name in file_names:
                    file_path = os.path.join(folder_name, file_name)
                    zip_file.write(file_path, os.path.relpath(file_path, new_dir))

        # Remove the copied "result" subdirectory
        shutil.rmtree(new_dir)


def rm_redundant_tex_files(main_directory):
    script_path = os.path.join(os.path.abspath("."), "scripts/rm_tex_files.sh")
    subprocess.run(["bash", script_path, main_directory], check=True)


def is_processed(tex_file):
    directory = os.path.dirname(tex_file)
    result_directory = os.path.join(directory, "output/result")
    if not os.path.exists(result_directory):
        return False

    png_files = glob.glob(f"{result_directory}/*.png")
    if png_files:
        return True

    return False


def parse_arguments():
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--path", type=str, required=True, help="The path to the main directory"
    )
    args = parser.parse_args()
    main_directory = args.path
    return main_directory


def main():
    main_directory = parse_arguments()
    script_path = os.path.join(os.path.abspath("."), "scripts/pipeline.sh")

    rm_redundant_tex_files(main_directory)

    extract_all_tar_gz(main_directory)
    tex_files = find_all_tex_files(main_directory)
    tex_files = preprocess_tex_files(tex_files)

    for tex_file in tex_files:
        log.debug(f"Running for tex file: {tex_file}")
        if is_processed(tex_file):
            log.debug(f"Tex file {tex_file} is already processed")
            continue
        subprocess.run(["bash", script_path, tex_file], check=True)

    destination_directory = os.path.expanduser("~/vrdu_data/annotations")
    extract_result(main_directory, destination_directory)


if __name__ == "__main__":
    main()
